#cloud-config
#
# Set up a Shiny server on Ubuntu 20.04 - without SSL certificate
# - see https://cloud.r-project.org/bin/linux/ubuntu/ for the choice of the Ubuntu version
# - also check the shiny server version number at https://www.rstudio.com/products/shiny/download-server/ubuntu/
#
# Creates a new user named "piet" with password-less sudo capabilities
# SSH is available on port 4444
#
# Log is saved as /var/log/cloud-init-output.log
#
# Check these things manually first:
#  - Make sure the R apt source matches the system
#    (see https://cran.rstudio.com/bin/linux/ubuntu/fullREADME.html for names)
#  - If running on smaller droplet uncomment the section that enlarges swapfile
#  - Optional: add SSH public key for user account
#
# Some checks to do after the cloud-init script has finished:
# - (SSH) Is SSH key added? sudo nano ~/.ssh/authorized_keys
# - (SSH) Has port changed from 22 to 4444? sudo nano /etc/ssh/sshd_config
# - (Nginx) Is the content of the server block written to the file that is included in the Nginx config file /etc/nginx/conf.d? sudo nano /etc/nginx/sites-enabled/default
# - Are .deb files deleted? sudo ls -l /var/cache/apt/archives
#   - If not, apply sudo apt-get clean (source: https://www.jverdeyen.be/ubuntu/digital-ocean-ubuntu-free-up-disk-space/)
# - (sed) Check sed syntax at https://sed.js.org/index.html, this tool was used to solve the issue with port 4444 (see commit w/ hash fcb426dd536952ce929329a865d737660d12f112)
#
# Help on cloud-init syntax from:
#  - https://cloudinit.readthedocs.io/en/latest/topics/examples.html
#  - https://www.digitalocean.com/community/tutorials/how-to-use-cloud-config-for-your-initial-server-setup
#    (ERROR: THE ssh-authorized-keys (AND sudo) SYNTAX IS WRONG **IN ALL DIGITAL OCEAN EXAMPLES**, SEE NEXT REFERENCE)
#  - https://superuser.com/questions/1725127/invalid-config-for-cloud-init-but-apparently-still-works-how-do-i-remove-the
#  - https://github.com/andrewheiss/cloud-config-files
#
# Help on Shiny server installation syntax from:
#  - http://deanattali.com/2015/05/09/setup-rstudio-shiny-server-digital-ocean/
#  - https://www.digitalocean.com/community/tutorials/how-to-set-up-shiny-server-on-ubuntu-20-04
#  - https://gist.github.com/mdlincoln/1f40f4e88ce32c55b5f3
#  - https://gist.github.com/mdlincoln/1f40f4e88ce32c55b5f3#gistcomment-3009981
#  - https://cran.rstudio.com/bin/linux/ubuntu/fullREADME.html#using-apt-key

# Add apt mirror to get the latest version of R necessary for Shiny
apt:
  sources:
    source1:
      source: "deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/"
      keyid: E298A3A825C0D65DFD57CBB651716619E084DAB9

package_upgrade: true
packages:
  - fail2ban
  - curl
  # Packages for R
  - r-base-dev
  - libcurl4-gnutls-dev
  - libxml2-dev
  - libssl-dev
  # Packages for Shiny server
  - nginx
  - gdebi-core
users:
  - name: piet
    # Add SSH key
    #ssh_authorized_keys:
    #  - ssh-rsa ... Main computer
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
write_files:
  - path: /etc/fail2ban/jail.local
    content: |
        [DEFAULT]
        # Ban hosts for one hour:
        bantime = 3600
        #
        # Override /etc/fail2ban/jail.d/00-firewalld.conf:
        banaction = iptables-multiport
        #
        [sshd]
        enabled = true
        port    = 4444
        logpath = %(sshd_log)s
  # Forward ports for Shiny
  - path: /etc/nginx/sites-enabled/default
    content: |
      # Mitigation Slow Read/Loris DDOS attack
      limit_conn_zone $binary_remote_addr zone=addr:10m;
      
      # Everything else...
      server {
        # Mitigation Slow Read/Loris DDOS attack
        client_body_timeout 5s;
        client_header_timeout 5s;
      
        # Everything else...
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        
        location / {
          # Mitigation Slow Read/Loris DDOS attack
          limit_conn addr 250;
          
          # Everything else...
          proxy_pass http://127.0.0.1:3838;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 20d;
        }
      }
runcmd:
  # Configure SSH and fail2ban
  - sed -i -e '/^[# ]*Port/s/^.*$/Port 4444/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers piet' /etc/ssh/sshd_config
  - sed -i -e '$aDebianBanner no' /etc/ssh/sshd_config
  - service ssh restart
  - service fail2ban restart
  # Prevent Nginx from showing its version number
  - sed -i -e '/^[# ]*server_tokens/s/^.*$/server_tokens off;/' /etc/nginx/nginx.conf
  # Set up a basic firewall, but allow SSH connections
  - ufw allow OpenSSH
  - ufw allow 'Nginx HTTP'
  # Replace this by the following line if port 443 should also be opened
  #- ufw allow 'Nginx Full'
  - ufw allow 4444/tcp
  - ufw --force enable
  # Get rid of message about how to run sudo
  - install -m 644 -o piet /dev/null /home/piet/.sudo_as_admin_successful
  # ### R stuff ###
  # Bigger swap file for R on smaller machines
  - /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
  - /sbin/mkswap /var/swap.1
  - /sbin/swapon /var/swap.1
  - sh -c 'echo "/var/swap.1 swap swap defaults 0 0 " >> /etc/fstab'
  # Install "shiny" package for R
  - R -e 'install.packages(c("shiny", "rmarkdown"), repos="https://cran.rstudio.com/")'
  # Download and install Shiny
  - wget https://download3.rstudio.org/ubuntu-18.04/x86_64/shiny-server-1.5.18.987-amd64.deb
  - gdebi -n shiny-server-1.5.18.987-amd64.deb
  # Clean package files
  - sudo apt-get clean
  - service nginx restart
