#cloud-config

package_upgrade: true
packages:
  - fail2ban
  - curl
  # Packages for Python
  - python3-pip
write_files:
  - path: /etc/fail2ban/jail.local
    content: |
        [DEFAULT]
        # Ban hosts for one hour:
        bantime = 3600
        #
        # Override /etc/fail2ban/jail.d/00-firewalld.conf:
        banaction = iptables-multiport
        #
        [sshd]
        enabled = true
        port    = 4444
        logpath = %(sshd_log)s
runcmd:
  # Configure SSH and fail2ban
  - sed -i -e '/^Port/s/^.*$/Port 4444/' /etc/ssh/sshd_config
  - service ssh restart
  - service fail2ban restart
  # Set up a basic firewall, but allow SSH connections
  - ufw allow OpenSSH
  - ufw allow 4444/tcp
  - ufw --force enable
  # ### Python package pptx2md ###
  - pip3 install pptx2md
